In [1]:
import numpy as np

In [7]:
n=np.arange(10)

In [9]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b=np.arange(2,10,2)

In [13]:
b

array([2, 4, 6, 8])

In [25]:
b.shape

(4,)

In [17]:
ar=np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [19]:
arr=np.array(
    [[1,2,3],
     [3,4,5]
    ]
)                              #2d dimension

In [21]:
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [23]:
arr.shape      #rows,columns

(2, 3)

In [29]:
arr.dtype

dtype('int32')

In [31]:
a=np.array([1,2,3], dtype=np.float32)

In [33]:
a

array([1., 2., 3.], dtype=float32)

In [37]:
a=np.zeros([1,2,3])

In [39]:
a

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
x=np.zeros((2,3,4))

In [43]:
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
x.ndim

3

In [49]:
x.size

24

In [51]:
x=np.full((2,2),4)
x

array([[4, 4],
       [4, 4]])

In [59]:
# opereations
asum=np.add([2,4,6],[3,5,7])
asum

array([ 5,  9, 13])

In [71]:
a=np.array([[1,2,3],[4,5,6],[7,8,9] ])

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
a.ndim

2

In [77]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [83]:
a[0:2,1:3]=[[10,23],[40,50]]

In [85]:
a

array([[ 1, 10, 23],
       [ 4, 40, 50],
       [ 7,  8,  9]])

In [87]:
#Boolean indexing allows you to select elements from an array based on a condition. You create a boolean mask indicating 
#which elements satisfy the condition, and then use this mask to extract the desired elements.
z=np.array([1,5,8,10,3,2])

In [89]:
z1=z>3

In [91]:
z1

array([False,  True,  True,  True, False, False])

In [93]:
z[z1]

array([ 5,  8, 10])

In [95]:
#Fancy indexing allows you to select elements from an array using arrays of indices. You provide arrays of
#indices along each axis, and the elements at those indices are returned as a new array.

z=np.array([1,5,8,10,3,2])



In [97]:
z1=[0,2,5]

In [99]:
z[z1]

array([1, 8, 2])

In [109]:
''' Transposing Arrays:
Transposing an array means exchanging its rows and columns. In NumPy,
you can transpose an array using the T attribute or the transpose() function.'''
Tra=np.array([
    [1,2,3],
    [4,5,6]
])
Tra


array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
Transpose=Tra.T


In [113]:
Tra.shape

(2, 3)

In [115]:
Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [117]:
Transpose.shape

(3, 2)

In [119]:
'''Swapping Axes:

Swapping axes means rearranging the dimensions of an array. You can swap axes using the swapaxes() function.'''
sw=np.array([[1,2,3],
             [4,5,6]])
sw

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
sw.shape

(2, 3)

In [123]:
swa=sw.swapaxes(0,1)

In [125]:
swa

array([[1, 4],
       [2, 5],
       [3, 6]])

In [127]:
swa.shape

(3, 2)

In [129]:
# Create a 3D array of shape (2, 3, 4)
# Think of it as 2 layers of 3x4 matrices
array_3d = np.array([[[ 1,  2,  3,  4],
                      [ 5,  6,  7,  8],
                      [ 9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print("Original array shape:", array_3d.shape)

Original array shape: (2, 3, 4)


In [135]:
array_3d.swapaxes(0,1)

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [143]:
#reshape
ar=np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr=ar.reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
''' Pseudo-random Number Generation:

NumPy provides various functions for generating pseudo-random numbers. These functions are located in the numpy.random module.
You can generate random numbers from different distributions, such as uniform, normal, binomial, etc.'''
ar=np.random.randint(1,100,size=5)
ar

array([96, 40, 21, 31, 43])

In [163]:
arr=np.random.normal(size=5)
arr

array([-0.19928812,  0.57761843,  0.14162282, -0.1706833 , -0.06688416])